image:
    file: .gitpod.Dockerfile

tasks:
    - init: ./gradlew clean build
    - command: ./gradlew run
    - command: export DEV_ENVIROMENT_HOST=`gp url 8080` java <application-entry>


ports:
    - port: 8080
      onOpen: open-preview

vscode:
    extensions:
      - vscjava.vscode-java-pack
